### PR TITLE
Add Archive

### PR DESCRIPTION
**Pull request by wast**
Add Archive data to BlogEtcReaderController index response.

This is to show usual blog archive. Still needs to do front-end for it.

### CODE REVIEW

**Comment by vhessam** [comment]
@wast
thanks for your contribution.
let me know what do you mean about Archive?

**Comment by wast** [comment]
For example:

https://woocommerce.com/posts/archives-page/#

**Comment by vhessam** [comment]
got it yes, this feature will be added thanks

**Comment by vhessam** [comment]
@wast please complete the PR with updating view files.
Many thanks

**Comment by wast** [comment]
Will do when I find time for it. Cheers.

**Comment by vhessam** [comment]
will do it sure. next week I have enough time next week at Friday

**Pull request closed without merging**
